### ISSUE TITLE
Support Implicit Flow

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/chrome-oauth-bearer-plugin#13]
....

**Comment by gilvegliach** [comment]
@hjacobs Good idea, I'll look into it.

**Comment by gilvegliach** [comment]
I want to work on this but I haven't had time in over two weeks so I add the label "help wanted".

**Comment by brandonweis** [comment]
Maybe I can take this, may I know what's needed to be done?

**Comment by pragmader** [comment]
IMO it must be a different extension, too many changes for this one. Either we have to support both authentication options in the settings dialog (which will make the code messy) or to implement another extension which would use the implicit OAuth 2.0 flow only.

For example, the access token will be expired very often and we need to show the dialog with the authentication form over and over again. Because it's really hard to automate due too some redirections and the authentication form-related features. We should not rely that all authentication forms from all possible authentication servers are the same. And it makes it tricky.

So, I would rather implement a new extension dedicated to the OAuth 2.0 implicit flow only.

**Comment by musiKk** [comment]
I'm not sure if adding a second authentication method would be something I consider messy. The two methods don't differ too much conceptually, it's just the bootstrapping that's different. I just hacked together a fork with the new version [here](https://github.com/musiKk/chrome-oauth-bearer-plugin/tree/use-refresh-tokens). It's doesn't implement actual authentication (use ztoken for that) but apart from that it works for me.

Maybe there is something usable in there. :smile:

**Comment by pragmader** [comment]
@musiKk the problem is that we can't use `ztoken` in this case to comply the security policies we have to use the real Implicit Flow requesting user credentials and redirecting to authentication form. Also, there are things specific for the company that are useless for external users.

**Comment by musiKk** [comment]
Yeah, I just hacked it together because I find the plugin very convenient and with the deactivation of the old tokens API, it stopped working.

**Comment by pragmader** [comment]
@musiKk basically, we have have hack days right now and @gilvegliach and me are working on the new extension.

**Comment by gilvegliach** [comment]
(closed because of the internal extension. Ask @pragmader for the url)
